name: Deploy GitHub Pages

on:
  push:
    branches: ["main"] # Altere para "master" se a sua branch principal tiver esse nome

  # Permite rodar esse workflow manualmente pela aba Actions
  workflow_dispatch:

# Define as permissões necessárias para o token do GitHub Actions
permissions:
  contents: read
  pages: write
  id-token: write

# Garante que cancels de deploys antigos aconteçam se você fizer pushes seguidos
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o GitHub Pages
        uses: actions/configure-pages@v5

      # ATENÇÃO AQUI: Usamos o upload-pages-artifact, e não o upload-artifact comum
      - name: Upload do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Ponto significa que o index.html está na raiz do seu projeto

      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
